name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Faz o checkout do código do repositório

      - name: Run Docker Compose with Tests
        uses: adambirds/docker-compose-action@v1.5.0 # Usa o Docker Compose para subir os serviços e executar os testes
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "app"
          test-command: "npm test && npm run cypress:run" # Executa os testes Jest e Cypress
