name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Faz o checkout do código do repositório

      - name: Use Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1 # Usa o Docker Compose para subir os serviços
        with:
          compose-file: docker-compose.yml

      - name: Run Docker Compose
        run: docker-compose up -d # Sobe os serviços

      - name: Run Jest tests
        run: docker-compose exec app npm test # Executa os testes Jest

      - name: Run Cypress tests
        run: docker-compose exec app npm run cypress:run # Executa os testes Cypress
