name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Faz o checkout do código do repositório

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # Configura o QEMU para emulação de arquitetura

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Configura o Docker Buildx
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v6 # Constrói e envia a imagem Docker para o registro local
        with:
          push: true
          tags: localhost:5000/name/app:latest

      - name: Inspect
        run: docker buildx imagetools inspect localhost:5000/name/app:latest # Inspeciona a imagem Docker

      - name: Use Docker Compose
        uses: docker/compose-action@v2 # Usa o Docker Compose para subir os serviços
        with:
          compose-file: docker-compose.yml
          run: up --build -d

      - name: Wait for services to be ready
        run: sleep 20 # Aguarda os serviços ficarem prontos

      - name: Run Jest tests
        run: docker-compose exec app npm test # Executa os testes Jest

      - name: Run Cypress tests
        run: docker-compose exec app npm run cypress:run # Executa os testes Cypress
